services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports: # hote:container
      - 8080:5173
    volumes:
      - ./client/src/:/app/src/
      - ./client/package.json:/app/package.json
      - ./client/vite.config.ts:/app/vite.config.ts
      - ./client/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Force le polling
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: npm run dev # lance ton script dev (hot reload)
    ports:
      - 5050:4000
    volumes:
      - ./server/src:/app/src # monte ton code source
      - /app/node_modules # évite d’écraser node_modules dans le conteneur
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend:4000'' --data ''{"query":"query { __typename }"}'' || exit 1',
        ]
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    container_name: postgres
    ports: # hote:container
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/postgresql/data
